# Finding the closest Planet

- From the co-ordinates for the 5 planets 
- And the observation point
- Find, which planet is closest to the observation point

In [1]:
import numpy as np

In [2]:
points = np.array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

points

array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

In [3]:
observation = np.array([2.8, 12.5])
observation

array([ 2.8, 12.5])

In [4]:
points - observation

array([[-2.8, -1.5],
       [-1.8, -0.5],
       [-0.8,  0.5],
       [ 0.2,  1.5],
       [ 1.2,  2.5]])

In [5]:
(points - observation) ** 2

array([[7.84, 2.25],
       [3.24, 0.25],
       [0.64, 0.25],
       [0.04, 2.25],
       [1.44, 6.25]])

In [6]:
np.sum((points - observation) ** 2, axis=1)

array([10.09,  3.49,  0.89,  2.29,  7.69])

In [7]:
dist = np.sum((points - observation) ** 2, axis=1) ** 0.5
dist

array([3.17647603, 1.86815417, 0.94339811, 1.5132746 , 2.77308492])

In [9]:
nearest_planet_index = dist.argmin()
nearest_planet_index

2

In [14]:
print("The nearest planet to the observation point is at:", points[nearest_planet_index])

The nearest planet to the observation point is at: [ 2 13]


In [11]:
points

array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

In [17]:
dist.argmin()

2