# Introduction to Numpy

We plan to learn

- difference between lists and numpy arrays
- slicing in numpy
- broadcasting in numpy

In [1]:
list_a = list(range(1, 6))
list_a

[1, 2, 3, 4, 5]

In [2]:
list_b = list(range(10, 60, 10))
list_b

[10, 20, 30, 40, 50]

## Perform element-wise addition of two lists

1 + 10 = 11

2 + 20 = 22

...

In [3]:
both = [0] * len(list_a)
both                

[0, 0, 0, 0, 0]

In [4]:
for idx,val in enumerate(list_a):
    both[idx] = list_a[idx] + list_b[idx]
    
both    

[11, 22, 33, 44, 55]

In [5]:
import numpy as np

In [6]:
vec_a = np.array(range(1, 6))
vec_a

array([1, 2, 3, 4, 5])

In [7]:
vec_b = np.array(range(10, 60, 10))
vec_b

array([10, 20, 30, 40, 50])

In [8]:
vec_c = vec_a + vec_b
vec_c

array([11, 22, 33, 44, 55])